//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use sea_orm::FromQueryResult;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "movie")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub director: String,
    pub cast: Vec<String>,
    pub genres: Vec<String>,
    #[sea_orm(column_type = "Text")]
    pub language: String,
    #[sea_orm(column_type = "Text")]
    pub region: String,
    pub release_date: Option<Date>,
    pub year: Option<i32>,
    pub date_added: Date,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub storage_path: String,
}

#[derive(DerivePartialModel, FromQueryResult, serde::Serialize)]
#[sea_orm(entity = "Entity")]
pub struct ListPartialModel {
    pub id: String,
    pub title: String,
    pub year: Option<i32>,
}

#[derive(DerivePartialModel, FromQueryResult, serde::Serialize)]
#[sea_orm(entity = "Entity")]
pub struct ItemPartialModel {
    pub id: String,
    pub title: String,
    pub director: String,
    pub cast: Vec<String>,
    pub genres: Vec<String>,
    pub language: String,
    pub region: String,
    pub release_date: Option<Date>,
    pub year: Option<i32>,
    pub date_added: Date,
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
