//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::movie::Entity as Movie;
pub use super::music::Entity as Music;
pub use super::music_playlist::Entity as MusicPlaylist;
pub use super::video::Entity as Video;
