//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use sea_orm::FromQueryResult;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[derive(serde::Serialize, serde::Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub hashed_password: String,
    #[sea_orm(column_type = "Text")]
    pub salt: String,
    pub administrator: bool,
}

#[derive(DerivePartialModel, FromQueryResult, serde::Serialize, serde::Deserialize)]
#[sea_orm(entity = "Entity")]
pub struct PartialModel {
    pub id: String,
    pub username: String,
    pub administrator: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
